Codex 10 heading
codexsit/codexsit.github.io pull request #21
Opened 2024-02-27 13:37 UTC by Miran-Firdausi

Closes #10 

Added Heading element
and added text to hero section
configured tailwind config to add gray color

2024-02-27 14:56 UTC, Achyut-0705 requested changes
Make necessary changes

2024-02-27 14:56 UTC, Achyut-0705 commented on src/assets/styles/index.css
> +  -webkit-text-stroke-color: #737373;
Use tailwind classes as vars - check from inpect element --> html --> css variables

2024-02-27 14:56 UTC, Achyut-0705 commented on src/components/Heading/index.jsx
> +function Heading({ headingText }) {
Heading is a component, prop should be text

2024-02-27 14:56 UTC, Achyut-0705 commented on src/components/Heading/index.jsx
> +        {headingText}
Same here

2024-02-27 14:56 UTC, Achyut-0705 commented on src/components/Heading/index.jsx
> +        {headingText}
Here as well

2024-02-27 14:56 UTC, Achyut-0705 commented on src/components/Heading/index.jsx
> +      <div className="xs:text-2xl sm:text-4xl lg:text-[3.75rem] text-foreground absolute w-full xs:bottom-[-10px] sm:bottom-[-18px] lg:bottom-[-12px]">
don't specify hard coded pixel values. instead use defaults provided by tailwind

2024-02-27 14:56 UTC, Achyut-0705 commented on src/pages/Home/index.jsx
> +  return <Hero />;
Hero is a non functional component, replace it with actual jsx

2024-02-27 14:56 UTC, Achyut-0705 commented on tailwind.config.js
> +      },
Use scheme as per object shared

primary: {
main: color
}

something like this

2024-02-28 05:13 UTC, Miran-Firdausi commented on src/components/Heading/index.jsx
> +function Heading({ headingText }) {
This is done.

2024-02-28 05:29 UTC, Miran-Firdausi commented on src/assets/styles/index.css
> +  -webkit-text-stroke-color: #737373;
I was not able to find the required tailwind variable.
The only thing i could find is those export variables are getting converted into this form.
![image](https://github.com/codeXsit/CodeX-Website/assets/75238590/9d6f82c4-13ed-403c-b02b-3dab68d66dd0)

Can you commit to this or help me figure out.

2024-02-28 16:51 UTC, Achyut-0705 approved these changes
LGTM!

2024-02-28 17:00 UTC, Achyut-0705 commented on src/assets/styles/index.css
> +  -webkit-text-stroke-color: #737373;
Will take care of this later

2024-02-28 17:00 UTC, merged