Added Loader
codexsit/codexsit.github.io pull request #40
Opened 2024-03-19 17:02 UTC by GenDelta

I added the following to the code: 
- Added a loader 
![image](https://github.com/codeXsit/CodeX-Website/assets/88091748/4c82303d-50b5-4354-aeb4-090465fec44b)

Closes #45 
Kindly review the changes,

2024-03-19 17:06 UTC, codexsit approved these changes
LGTM!

2024-03-19 17:06 UTC, codexsit commented on src/components/Loader/index.css
> +    background-color: #212022;
use class/id and not tag selector

2024-03-19 17:06 UTC, codexsit requested changes
made suggested changes

2024-09-12 15:36 UTC, Miran-Firdausi commented
Different Pre-loader implemented in #65

2024-09-12 15:36 UTC, closed without merging