Codex 3 events
codexsit/codexsit.github.io pull request #42
Opened 2024-03-20 17:54 UTC by Dios-001

2024-03-21 17:11 UTC, codexsit requested changes
Make necessary changes

2024-03-21 17:11 UTC, codexsit commented on src/components/Navbar/index.jsx
why is there a change in navbar component when u were working on events page/route

2024-03-21 17:11 UTC, codexsit commented on src/pages/Events/index.jsx
> +  }, []);
no need to use `useEffect`, directly assign userData to useState

2024-03-21 17:11 UTC, codexsit commented on src/pages/Events/index.jsx
> +  const [users, setUsers] = useState([]);
Shouldn't this be events and not user?

2024-03-22 09:48 UTC, Dios-001 commented on src/components/Navbar/index.jsx
my bad, assumed that everyone had to put their link into navbar component, apart from that on app.jsx i had made one change to routes/index.jsx, added route to events page, should i delete em?

2024-09-08 14:49 UTC, merged