feat: Page not found page
codexsit/codexsit.github.io pull request #44
Opened 2024-03-25 14:55 UTC by Miran-Firdausi

Closes: #24 
Added page not found page
Preview:
![image](https://github.com/codeXsit/CodeX-Website/assets/75238590/ec092dea-c02e-4a6f-a4e1-6b0ca669ebb6)

2024-03-25 15:00 UTC, Achyut-0705 requested changes
Do the necessary changes

2024-03-25 15:00 UTC, Achyut-0705 commented on src/pages/PageNotFound/index.css
Remove empty file

2024-03-25 15:00 UTC, Achyut-0705 commented on src/pages/PageNotFound/index.jsx
> +function PageNotFound({ text, link }) {
Define prop types

2024-03-25 15:00 UTC, Achyut-0705 commented on src/pages/PageNotFound/index.jsx
> +          src={error404Image}
Set alt text

2024-03-25 15:02 UTC, Achyut-0705 requested changes

2024-03-25 15:02 UTC, Achyut-0705 commented on src/pages/PageNotFound/index.jsx
> +function PageNotFound({ text, link }) {
Do we need text nd link? Isn't this a static page?
If u want to add url then get it via url

2024-03-25 15:21 UTC, Miran-Firdausi commented on src/pages/PageNotFound/index.jsx
> +function PageNotFound({ text, link }) {
Accidentaly pushed the previous version, there is no need of text and link.

2024-03-25 15:22 UTC, Miran-Firdausi commented on src/pages/PageNotFound/index.jsx
> +function PageNotFound({ text, link }) {
No props were required

2024-03-25 15:23 UTC, Miran-Firdausi commented
I have made all the necessary changes

2024-03-30 16:45 UTC, codexsit approved these changes
LGTM!

2024-03-30 16:46 UTC, Achyut-0705 approved these changes
LGTM!

2024-03-30 16:47 UTC, merged